import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

// ** Theme
import ThemeComponent from "../@core/theme";

// ** Context
import { SettingProvider } from "../@core/contexts/setting-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <body>
          <SettingProvider>
            <ThemeComponent>{children}</ThemeComponent>;
          </SettingProvider>
        </body>
      </AppRouterCacheProvider>
    </html>
  );
}
