import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

// ** Theme
import ThemeComponent from "../@core/theme";

// ** Context
import { SettingProvider } from "../@core/contexts/setting-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "en-US" }, { lang: "de" }];
}

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: any;
}>) {
  console.log(params);
  return (
    <html lang={params.lang}>
      <AppRouterCacheProvider>
        <body>
          <SettingProvider>
            <ThemeComponent>{children}</ThemeComponent>
          </SettingProvider>
        </body>
      </AppRouterCacheProvider>
    </html>
  );
}
